<?php

namespace Database\Seeders;

use App\Models\Sale;
use Illuminate\Database\Seeder;

class SaleSeeder extends Seeder
{
    public function run(): void
    {
        Sale::insert([
            [
                'user_id' => 2, // cashier id
                'invoice_no' => 'SAL-1001',
                'subtotal' => 1000,
                'discount' => 0,
                'tax' => 50,
                'total' => 1050,
                'paid_amount' => 1100,
                'change_return' => 50,
            ],
            [
                'user_id' => 3,
                'invoice_no' => 'SAL-1002',
                'subtotal' => 750,
                'discount' => 50,
                'tax' => 35,
                'total' => 735,
                'paid_amount' => 740,
                'change_return' => 5,
            ],
            [
                'user_id' => 4,
                'invoice_no' => 'SAL-1003',
                'subtotal' => 1200,
                'discount' => 100,
                'tax' => 55,
                'total' => 1155,
                'paid_amount' => 1200,
                'change_return' => 45,
            ],
            [
                'user_id' => 5,
                'invoice_no' => 'SAL-1004',
                'subtotal' => 500,
                'discount' => 0,
                'tax' => 25,
                'total' => 525,
                'paid_amount' => 530,
                'change_return' => 5,
            ],
            [
                'user_id' => 6,
                'invoice_no' => 'SAL-1005',
                'subtotal' => 950,
                'discount' => 50,
                'tax' => 45,
                'total' => 945,
                'paid_amount' => 950,
                'change_return' => 5,
            ],
            [
                'user_id' => 7,
                'invoice_no' => 'SAL-1006',
                'subtotal' => 300,
                'discount' => 0,
                'tax' => 15,
                'total' => 315,
                'paid_amount' => 320,
                'change_return' => 5,
            ],
            [
                'user_id' => 8,
                'invoice_no' => 'SAL-1007',
                'subtotal' => 1100,
                'discount' => 100,
                'tax' => 50,
                'total' => 1050,
                'paid_amount' => 1100,
                'change_return' => 50,
            ],
            [
                'user_id' => 9,
                'invoice_no' => 'SAL-1008',
                'subtotal' => 400,
                'discount' => 20,
                'tax' => 18,
                'total' => 398,
                'paid_amount' => 400,
                'change_return' => 2,
            ],
            [
                'user_id' => 10,
                'invoice_no' => 'SAL-1009',
                'subtotal' => 600,
                'discount' => 30,
                'tax' => 28,
                'total' => 598,
                'paid_amount' => 600,
                'change_return' => 2,
            ],
            [
                'user_id' => 11,
                'invoice_no' => 'SAL-1010',
                'subtotal' => 850,
                'discount' => 50,
                'tax' => 40,
                'total' => 840,
                'paid_amount' => 850,
                'change_return' => 10,
            ],
            [
                'user_id' => 12,
                'invoice_no' => 'SAL-1011',
                'subtotal' => 200,
                'discount' => 0,
                'tax' => 10,
                'total' => 210,
                'paid_amount' => 220,
                'change_return' => 10,
            ],
            [
                'user_id' => 13,
                'invoice_no' => 'SAL-1012',
                'subtotal' => 1300,
                'discount' => 100,
                'tax' => 60,
                'total' => 1260,
                'paid_amount' => 1300,
                'change_return' => 40,
            ],
            [
                'user_id' => 14,
                'invoice_no' => 'SAL-1013',
                'subtotal' => 700,
                'discount' => 20,
                'tax' => 33,
                'total' => 713,
                'paid_amount' => 720,
                'change_return' => 7,
            ],
            [
                'user_id' => 15,
                'invoice_no' => 'SAL-1014',
                'subtotal' => 450,
                'discount' => 0,
                'tax' => 22,
                'total' => 472,
                'paid_amount' => 475,
                'change_return' => 3,
            ],
            [
                'user_id' => 16,
                'invoice_no' => 'SAL-1015',
                'subtotal' => 1000,
                'discount' => 50,
                'tax' => 48,
                'total' => 998,
                'paid_amount' => 1000,
                'change_return' => 2,
            ],
            [
                'user_id' => 17,
                'invoice_no' => 'SAL-1016',
                'subtotal' => 550,
                'discount' => 25,
                'tax' => 26,
                'total' => 551,
                'paid_amount' => 555,
                'change_return' => 4,
            ],
            [
                'user_id' => 18,
                'invoice_no' => 'SAL-1017',
                'subtotal' => 800,
                'discount' => 40,
                'tax' => 38,
                'total' => 798,
                'paid_amount' => 800,
                'change_return' => 2,
            ],
            [
                'user_id' => 19,
                'invoice_no' => 'SAL-1018',
                'subtotal' => 950,
                'discount' => 30,
                'tax' => 46,
                'total' => 966,
                'paid_amount' => 970,
                'change_return' => 4,
            ],
            [
                'user_id' => 20,
                'invoice_no' => 'SAL-1019',
                'subtotal' => 400,
                'discount' => 10,
                'tax' => 19,
                'total' => 409,
                'paid_amount' => 410,
                'change_return' => 1,
            ],
            
        ]);
    }
}